#!/usr/bin/env node
/**
 *  nc-start.js
 *
 *  This is a shell script will start NetCreate
 *  directly.
 *  
 *  It assums that the app has been built.
 *
 *  It is used in multi-db environments to start up
 *  multiple nc.js instances.
 *
 */

const shell = require("shelljs");

const pathToNetcreate = './netcreate-2018/build';


function writeConfig(data) {
  const { db, port, netport, ip, googlea } = data;
  
  const dataset = db;
  const netportDef = netport ? `\n  netport: "${netport}",` : '';
  const ipDef = ip ? `\n  ip: "${ip}",` : '';

  let script = `
// this file generated by NC command
const NC_CONFIG = {
  dataset: "${dataset}",
  port: "${port}",${netportDef}${ipDef}
  googlea: "${googlea}"
};
if (typeof process === "object") module.exports = NC_CONFIG;
if (typeof window === "object") window.NC_CONFIG = NC_CONFIG;`;
  shell.ShellString(script).to(`${pathToNetcreate}/app/assets/netcreate-config.js`);
}

function promiseServer(port) {
  shell.cd('netcreate-2018/build');
  const server = require(`${pathToNetcreate}/brunch-server`);
  return new Promise((resolve, reject) => {
    server({ port: port }, function () {
      console.log(`\n*** NetCreate is running (classroom mode) on port ${port} ***\n`);
      resolve();
    });
  });
}

async function startServer(port) {
  await promiseServer(port);
  console.log("### nc-start.js: 3. Server started.!");
  process.send("nc-start.js: Completed!");  
}

process.on("message", (data) => {
  console.log('###');
  console.log("### nc-start.js: STARTING DB", data.db);
  console.log("###");

  console.log("### nc-start.js: 1. Setting netcreate-config.js.");
  writeConfig(data);
  
  console.log("### nc-start.js: 2. Starting server");
  startServer(data.port);
});
